#!/bin/sh
# this xrandr shell script generated by arandr
# for use with ASUS U36JC with external VGA monitor
xrandr --output LVDS-1-1 --primary --mode 1366x768 --pos 1280x256 --rotate normal --output DP-1-1 --off --output VGA-1-1 --mode 1280x1024 --pos 0x0 --rotate normal --output HDMI-1-1 --off --output HDMI-0 --off
