#!/bin/bash
#~/.bash_profile
#
# Config for login shells (run at initial connection)

if [ -f ~/.bashrc ]; then
  #shellcheck source=/home/junbuntu/.bashrc
  source ~/.bashrc
fi

source "$HOME/.cargo/env"
