# yaml config for k9s cluster mgmt frontend for k8s
# original path: ~/.config/k9s/config.yaml
k9s:
  refreshRate: 2
  maxConnRetry: 5
  enableMouse: false
  headless: false
  logoless: false
  crumbsless: false
  readOnly: false
  noExitOnCtrlC: false
  noIcons: false
  skipLatestRevCheck: false
  logger:
    tail: 100
    buffer: 5000
    sinceSeconds: 300
    fullScreenLogs: false
    textWrap: false
    showTime: false
  currentContext: default
  currentCluster: default
  clusters:
    default:
      namespace:
        active: kube-system
        lockFavorites: false
        favorites:
        - kube-system
        - kubernetes-dashboard
        - all
        - default
      view:
        active: pods
      featureGates:
        nodeShell: true
      shellPod:
        image: busybox:1.35.0
        command:
        - ash
        args: []
        namespace: default
        limits:
          cpu: 100m
          memory: 100Mi
        labels: {}
      portForwardAddress: localhost
  thresholds:
    cpu:
      critical: 90
      warn: 70
    memory:
      critical: 90
      warn: 70
  screenDumpDir: /tmp/k9s-screens-jundora
