#!/bin/bash
# Launch Script for OmegaT CAT tool
# GOOGTRANS and MSTRANS represent the API
# keys for Google Translate API v2 and
# Microsoft Translator, respectively

GOOGTRANS=$(<$HOME/passwords/googleTranslateAPIkey.pw)
MSTRANS=$(<$HOME/passwords/microsoftTranslatorAPIkey.pw)
OTPATH=$HOME/ot351
XMODIFIERS=@im=ibus java -jar -Xmx512M -Dgoogle.api.key=$GOOGTRANS -Dmicrosoft.api.client_id=omegat_KE -Dmicrosoft.api.client_secret=$MSTRANS -Dswing.crossplatformlaf=com.sun.java.swing.plaf.gtk.GTKLookAndFeel $OTPATH/OmegaT.jar
