# starship.toml for Macbook Pro M1 work laptop
#
# Original path to file is ~/.config/starship.toml
#
# Created on: 01 Aug 2024
# Created by: gopeterjun@naver.com
# Last Updated: 01 Aug 2024


[gcloud]
format = 'on [$symbol$account(@$domain)(\($project\))]($style) '
