#!/usr/bin/env bash
# ~/.bashrc for MacOS
#
# Created On: Sometime during Nov 2019
# Created by: gopeterjun@naver.com
# Last Updated: Sun 18 Jan 2026

# If not running interactively, don't do anything
#[[ $- != *i* ]] && return

# don't put duplicate lines or lines starting with space in the history.
# See bash(1) for more options
HISTCONTROL=ignoreboth

# append to the history file, don't overwrite it
shopt -s histappend

HISTSIZE=10000
HISTFILESIZE=15000

export EDITOR="/opt/homebrew/bin/emacsclient"
#export TERM=screen-256color
export TERM=xterm-256color

eval "$(/opt/homebrew/bin/starship init bash)"
# Only execute if this is an interactive shell
if [[ $- == *i* ]]; then
  /opt/homebrew/bin/fastfetch
fi

eval "$(fzf --bash)"
# C-t fuzzy file/dir selection
# C-r fuzzy history search
# M-c fuzzy `cd`
# ** <TAB> fuzzy completion in shell command

source ~/.bash_aliases
# vim: ts=2 sw=2 et :

