#!/usr/bin/env bash
# ~/.bashrc for MacOS
#
# Created On: Sometime during Nov 2019
# Created by: gopeterjun@naver.com
# Last Updated: Sat 01 Nov 2025

# If not running interactively, don't do anything
#[[ $- != *i* ]] && return

# don't put duplicate lines or lines starting with space in the history.
# See bash(1) for more options
HISTCONTROL=ignoreboth

# append to the history file, don't overwrite it
shopt -s histappend

HISTSIZE=10000
HISTFILESIZE=15000

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize


export EDITOR="/usr/local/bin/emacsclient"
#export TERM=screen-256color
export TERM=xterm-256color
# Prompt: "user@hostname CurrentWorkingDirectory $ " no color
#PS1='[\u@\h \W]\$ '
# Same as above, but user@host in green, CWD in blue
#PS1="\[\033[01;32m\]\u@\h\[\033[00m\] \[\033[01;34m\]\W\[\033[00m\]\$ "
# Prompt: "user@host:" in green, "full path to CWD" in blue
#PS1="\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ "

eval "$(starship init bash)"
# Only execute neofetch if this is an interactive shell
if [[ $- == *i* ]]; then
  fastfetch
fi

source ~/.bash_aliases
# vim: ts=2 sw=2 et :

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
