#!/usr/bin/bash
# Per-user `~/.bash_profile` for argonaut running Fedora
#
# Created on: Sun 05 Jan 2025
# Created by gopeterjun
# Last Updated: Sun 19 Oct 2025
#
# These settings are sourced by the login shell

if [ -f ~/.bashrc ]; then
  # SC override is to quiet the warning about following path to source
  # shellcheck disable=SC1091
  source "$HOME"/.bashrc
fi

GPG_TTY=$(tty)
export GPG_TTY
export GOROOT=/usr/local/go  # consider moving this to the system `bash_profile`
export GOPATH=$HOME/go
export PYENV_ROOT="$HOME/.pyenv"
export PYTHONBREAKPOINT=ipdb.set_trace
export PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:$GOPATH/bin:$GOROOT/bin:$HOME/.local/bin:$HOME/bin:$PYENV_ROOT/bin:$HOME/.tfenv/bin:$HOME/.krew/bin"
export SSH_AUTH_SOCK=/run/user/1000/ssh-agent.socket
# NOTE: if GNOME keyring is installed, you must deactivate its ssh component
# otw it will overwrite SSH_AUTH_SOCK above
if pidof sway; then
  export SWAYSOCK=/run/user/$UID/sway-ipc.${UID}."$(pidof sway)".sock
fi
LANG=en_US.UTF-8
LC_ALL=en_US.UTF-8
export TERM=xterm-256color
# fcitx5 IME variables for Wayland Desktop
export XDG_SESSION_TYPE=wayland
export XDG_CONFIG_HOME=$HOME/.config
export GTK_IM_MODULE=fcitx
export QT_IM_MODULE=fcitx
export QT_IM_MODULES="wayland;fcitx;"
export XMODIFIERS="@im=fcitx"
export KUBECONFIG=$HOME/.kube/config
export EDITOR="emacsclient -nw"

# add ssh privkeys to ssh-agent
# if you use a graphical session manager, the screen may go dark
# while the shell waits for you to enter your ssh privkey password
#ssh-add ~/.ssh/archjun-newgen

# shellcheck source=/dev/null
if [ -e "$HOME"/.nix-profile/etc/profile.d/nix.sh ]; then . "$HOME"/.nix-profile/etc/profile.d/nix.sh; fi # added by Nix installer
eval "$(pyenv init --path)"
