#!/usr/bin/env bash
# Per-user `~/.bash_profile` for Asahilinux Fedora
#
# Created on: 28 Apr 2024
# Created by gojun077
# Last Updated: 20 Aug 2024
#
# These settings are sourced by the login shell

if [ -f ~/.bashrc ]; then
  # SC override is to quiet the warning about following path to source
  # shellcheck disable=SC1091
  source "$HOME"/.bashrc
fi

GPG_TTY=$(tty)
export GPG_TTY
export GOROOT=/usr/local/go  # consider moving this to the system `bash_profile`
export GOPATH=$HOME/go
export PYTHONBREAKPOINT=ipdb.set_trace
export PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:$GOPATH/bin:$GOROOT/bin:$HOME/.local/bin:$HOME/bin:$HOME/.tfenv/bin:$HOME/.krew/bin"
export SSH_AUTH_SOCK="/run/user/1000/ssh-agent.socket"
# NOTE: if GNOME keyring is installed, you must deactivate its ssh component
# otw it will overwrite SSH_AUTH_SOCK above
export TERM=xterm-256color
# fcitx5 IME variables for Wayland Desktop
export XDG_SESSION_TYPE=wayland
export XDG_CONFIG_HOME=$HOME/.config
export GTK_IM_MODULE=fcitx
export QT_IM_MODULE=fcitx
export QT_IM_MODULES="wayland;fcitx;"
export XMODIFIERS="@im=fcitx"
export KUBECONFIG=$HOME/.kube/config
export EDITOR="emacsclient -nw"

# add ssh privkeys to ssh-agent
ssh-add ~/.ssh/archjun-newgen

if [ -e /home/jundora/.nix-profile/etc/profile.d/nix.sh ]; then . /home/jundora/.nix-profile/etc/profile.d/nix.sh; fi # added by Nix installer
