#!/usr/bin/env bash
# Per-user `~/.bash_profile` for Ubuntu on Oracle Cloud
#
# Created on: 29 Jul 2024
# Created by: gopeterjun@naver.com
# Last Updated: 18 Dec 2024
#
# These settings are sourced by the login shell

if [ -f ~/.bashrc ]; then
  # SC override is to quiet the warning about following path to source
  # shellcheck disable=SC1091
  source "$HOME"/.bashrc
fi

GPG_TTY=$(tty)
export GPG_TTY
export GOROOT=/usr/local/go  # consider moving this to the system `bash_profile`
export GOPATH="$HOME/go"
export KUBECONFIG="$HOME/.kube/config"
export PYENV_ROOT="$HOME/.pyenv"
export PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin:$GOPATH/bin:$GOROOT/bin:$HOME/.local/bin:$HOME/bin"

export SSH_AUTH_SOCK=/run/user/1001/ssh-agent.socket
ssh-add -l &>/dev/null
if [[ $? -eq 0 || $? -eq 1 ]]; then
  echo "SSH agent already running with socket $SSH_AUTH_SOCK"
  return 0
fi

echo "Socket exists but agent not responding, removing socket"
rm -f "$SSH_AUTH_SOCK"
# No agent running or socket not working, start a new one
echo "Starting new SSH agent"
ssh-agent -D -a "$SSH_AUTH_SOCK" > /dev/null

# NOTE: if GNOME keyring is installed, you must deactivate its ssh component
# otw it will overwrite SSH_AUTH_SOCK above
export TERM=xterm-256color
export EDITOR="emacsclient -nw"
