#!/usr/bin/env bash
# ~/.bashrc for Asahi Linux (Apple Silicon Macs)
#
# Created On: 30 Apr 2024
# Created by: gopeterjun@naver.com
# Last Updated: Sun 15 Mar 2026

# If not running interactively, don't do anything
#[[ $- != *i* ]] && return

# don't put duplicate lines or lines starting with space in the history.
# See bash(1) for more options
HISTCONTROL=ignoreboth

# append to the history file, don't overwrite it
shopt -s histappend

HISTSIZE=10000
HISTFILESIZE=15000

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# Prompt: "user@hostname CurrentWorkingDirectory $ " no color
#PS1='[\u@\h \W]\$ '

# Same as above, but user@host in green, CWD in blue
#PS1="\[\033[01;32m\]\u@\h\[\033[00m\] \[\033[01;34m\]\W\[\033[00m\]\$ "

# Same as above, but user@host in green, CWD in blue
#PS1="\[\033[01;32m\]\u@\h\[\033[00m\] \[\033[01;34m\]\W\[\033[00m\]\$ "

eval "$(starship init bash)"
# shellcheck disable=SC1090
source ~/.bash_aliases
# Only show output if this is an interactive shell AND not being used
# by automation
if [[ $- == *i* ]]; then
  fastfetch
  mbcputemp="$(cat /sys/class/thermal/thermal_zone0/temp)"
  printf "%s\\n" "CPU temp: $((mbcputemp/1000)) C"
fi

# function to enable the shell to send information to emacs 'vterm'
# via properly escaped sequences.
vterm_printf() {
    if [ -n "$TMUX" ] \
        && { [ "${TERM%%-*}" = "tmux" ] \
            || [ "${TERM%%-*}" = "screen" ]; }; then
        # Tell tmux to pass the escape sequences through
        printf "\ePtmux;\e\e]%s\007\e\\" "$1"
    elif [ "${TERM%%-*}" = "screen" ]; then
        # GNU screen (screen, screen-256color, screen-256color-bce)
        printf "\eP\e]%s\007\e\\" "$1"
    else
        printf "\e]%s\e\\" "$1"
    fi
}
# vim: ts=2 sw=2 et :
