#!/usr/bin/bash
# ~/.bashrc for Asahi Linux (Apple Silicon Macbook Pro M1)
#
# Created On: 30 Apr 2024
# Created by: gopeterjun@naver.com
# Last Updated: Fri 22 Aug 2025

# If not running interactively, don't do anything
#[[ $- != *i* ]] && return

# don't put duplicate lines or lines starting with space in the history.
# See bash(1) for more options
HISTCONTROL=ignoreboth

# append to the history file, don't overwrite it
shopt -s histappend

HISTSIZE=10000
HISTFILESIZE=15000

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# Prompt: "user@hostname CurrentWorkingDirectory $ " no color
#PS1='[\u@\h \W]\$ '

# Same as above, but user@host in green, CWD in blue
#PS1="\[\033[01;32m\]\u@\h\[\033[00m\] \[\033[01;34m\]\W\[\033[00m\]\$ "

# Same as above, but user@host in green, CWD in blue
#PS1="\[\033[01;32m\]\u@\h\[\033[00m\] \[\033[01;34m\]\W\[\033[00m\]\$ "

eval "$(starship init bash)"
eval "$(fzf --bash)"  # enable 'fzf' shell integration

# the following is to quiet error for SC1091, SC1090 'cannot follow dynamic paths'
# shellcheck source=/dev/null
source "$HOME/.bash_aliases"
# comment out neofetch to prevent banner from running twice
#neofetch
# Only execute neofetch if this is an interactive shell
if [[ $- == *i* ]]; then
  neofetch
  mbcputemp="$(cat /sys/class/thermal/thermal_zone0/temp)"
  printf "%s\\n" "CPU temp: $((mbcputemp/1000)) C"
fi
# vim: ts=2 sw=2 et :

export NVM_DIR="$HOME/.config/nvm"
# shellcheck source=/home/jundora/.config/nvm/nvm.sh
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
# shellcheck source=/home/jundora/.config/nvm/bash_completion
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

# pnpm
export PNPM_HOME="/home/jundora/.local/share/pnpm"
case ":$PATH:" in
  *":$PNPM_HOME:"*) ;;
  *) export PATH="$PNPM_HOME:$PATH" ;;
esac
# pnpm end

# Set NODE_PATH to include global npm modules
npm_root=$(npm root -g)
export NODE_PATH=$npm_root:$NODE_PATH
