#!/usr/bin/env bash
# bash_aliases_asahi
# Created on: Apr 30 2024
# Created by: gopeterjun@naver.com
# Last Updated: Mon 20 Oct 2025
#
# .bash_aliases for Asahi Linux intended to be sourced by .bashrc

alias ㅊㅇ='cd'
alias 니='ls'
alias ㅣㄴ='ls'
alias hazip='curl https://icanhazip.com'
alias ls='ls --color=auto'
#alias chromium-browser='chromium-browser --ozone-platform=wayland --enable-wayland-ime'
alias auggief='auggie --mcp-config ~/dotfiles/mcp/mcpservers.json'
alias code='code --ozone-platform=wayland'
alias codex='codex --sandbox workspace-write'
alias enox='emacsclient -nw'

ansicat() {
  if [ -f "$1" ]; then
    infile="$1"
    if [ -n "$2" ]; then
      ansifilter -i "$infile" -o "$2"
    else
      ansifilter -i "$infile"| less -R
    fi
  else
    printf "%s\\n" "File not found: $infile"
    printf "%s\\n" "## USAGE: ansicat <inputfile> (outputfile) ##"
    printf "%s\\n" "(outputfile) is optional argument"
  fi
}

# disable warning about non-constant path
# shellcheck disable=SC1090
source ~/.bash_aliases_secure  # this file is not stored in version control

if [ -f ~/.bash_aliases_macbookair ]; then
  # shellcheck disable=SC1090
  source ~/.bash_aliases_macbookair  # aliases for personal Macbook Air M2
fi
