#!/usr/bin/env bash
# ~/.bashrc for Ubuntu ARM on Oracle Cloud
#
# Created On: 29 Jul 2024
# Created by: gopeterjun@naver.com
# Last Updated: 29 Jul 2024

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

# don't put duplicate lines or lines starting with space in the history.
# See bash(1) for more options
HISTCONTROL=ignoreboth

# append to the history file, don't overwrite it
shopt -s histappend

HISTSIZE=10000
HISTFILESIZE=15000

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

function _update_ps1() {
  PS1="$(/usr/local/bin/powerline-go \
    -error $? \
    -cwd-max-depth 3 \
    -hostname-only-if-ssh \
    -max-width 95 \
    -jobs $(jobs -p | wc -l))"

    # Uncomment the following line to automatically clear errors after showing
    # them once. This not only clears the error for powerline-go, but also for
    # everything else you run in that shell. Don't enable this if you're not
    # sure this is what you want.

    #set "?"
}

if [ "$TERM" != "linux" ] && [ -f "/usr/bin/powerline-go" ]; then
    PROMPT_COMMAND="_update_ps1; $PROMPT_COMMAND"
fi

source ~/.bash_aliases