#!/bin/bash
#~/.bash_profile_ubuntu
#
# Last Updated: Apr 8 2023
#
# Config for interactive login shell (run at initial connection)


if [ -f ~/.bash_aliases  ]; then
  #shellcheck source=$HOME/dotfiles/bash_aliases
  source ~/.bash_aliases
fi

if [ -f ~/"SpiderOak Hive/bashrc_secure/bash_aliases_secure" ]; then
  #shellcheck source=$HOME/dotfiles/bash_aliases
  source ~/"SpiderOak Hive/bashrc_secure/bash_aliases_secure"
fi

# if running bash
if [ -n "$BASH_VERSION" ]; then
    # include .bashrc if it exists
    if [ -f "$HOME/.bashrc" ]; then
      . "$HOME/.bashrc"
    fi
fi

# set PATH so it includes user's private bin if it exists
if [ -d "$HOME/bin" ] ; then
    PATH="$HOME/bin:$PATH"
fi

# set PATH so it includes user's private bin if it exists
if [ -d "$HOME/.local/bin" ] ; then
    PATH="$HOME/.local/bin:$PATH"
fi

export BROWSER=firefox
export EDITOR=vim
export TERM=xterm-256color
export WINEPREFIX=/MULTIMEDIA/wine
GPG_TTY=$(tty)
export GPG_TTY
export GOROOT=/usr/local/go
export GOPATH="$HOME/go"
export PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin:/usr/games:$GOPATH/bin:$GOROOT/bin:$PATH"

