#!/usr/bin/env bash
# Per-user `~/.bash_profile` for Fedora aarch64 RPi4B
#
# Created on: 08 Apr 2022
# Created by gojun077
# Last Updated: 28 Sep 2024
#
# These settings are sourced by the login shell

if [ -f ~/.bashrc ]; then
  # SC override is to quiet the warning about following path to source
  # shellcheck disable=SC1091
  source "$HOME"/.bashrc
fi

GPG_TTY=$(tty)
export GPG_TTY
export GOROOT=/usr/local/go  # consider moving this to the system `bash_profile`
export GOPATH=$HOME/go
export PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:$GOPATH/bin:$GOROOT/bin:$HOME/.local/bin:$HOME/bin:$HOME/:$HOME/.krew/bin"
export SSH_AUTH_SOCK=/run/user/1000/ssh-agent.socket
# NOTE: if GNOME keyring is installed, you must deactivate its ssh component
# otw it will overwrite SSH_AUTH_SOCK above
export TERM=xterm-256color
export KUBECONFIG=$HOME/.kube/config
export EDITOR="vim"
