#!/usr/bin/env bash
# ~/.bashrc for Argo Fedora 40 amd64
#
# Created On: 30 Apr 2024
# Created by: gopeterjun@naver.com
# Last Updated: Thu 09 Jan 2025

# If not running interactively, don't do anything
#[[ $- != *i* ]] && return

# don't put duplicate lines or lines starting with space in the history.
# See bash(1) for more options
HISTCONTROL=ignoreboth

# append to the history file, don't overwrite it
shopt -s histappend

HISTSIZE=10000
HISTFILESIZE=15000

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# Prompt: "user@hostname CurrentWorkingDirectory $ " no color
#PS1='[\u@\h \W]\$ '

# Same as above, but user@host in green, CWD in blue
#PS1="\[\033[01;32m\]\u@\h\[\033[00m\] \[\033[01;34m\]\W\[\033[00m\]\$ "

# Same as above, but user@host in green, CWD in blue
#PS1="\[\033[01;32m\]\u@\h\[\033[00m\] \[\033[01;34m\]\W\[\033[00m\]\$ "

# https://unix.stackexchange.com/questions/470860/how-to-make-tty-work-in-bash-profile
export GPG_TTY="$(tty)"
if pidof sway; then
  export SWAYSOCK=/run/user/$UID/sway-ipc.${UID}."$(pidof sway)".sock
fi
eval "$(starship init bash)"
source ~/.bash_aliases
neofetch
# vim: ts=2 sw=2 et :
